# This file and its contents are licensed under the Apache License 2.0.
# Please see the included NOTICE for copyright information and LICENSE for a copy of the license.

{{- /*
This ConfigMap contains the full Patroni configuration - excluding the credentials for users.
*/ -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  patroni.yaml: |
{{ .Values | toYaml | indent 4 }}
...
