apiVersion: v1
entries:
  timescaledb-multinode:
  - apiVersion: v1
    created: "2020-01-08T11:03:18.42716669+01:00"
    description: TimescaleDB Multinode Deployment.
    digest: a6c664a75489e069cdd2d36dff87ca6d2b3a38a3edf16de4234418b354e40eea
    home: https://github.com/timescale/timescaledb-kubernetes
    maintainers:
    - email: support@timescale.com
      name: TimescaleDB
    name: timescaledb-multinode
    sources:
    - https://github.com/timescale/timescaledb-kubernetes
    - https://github.com/timescale/timescaledb-docker-ha
    - https://github.com/zalando/patroni
    urls:
    - timescaledb-multinode-0.3.0.tgz
    version: 0.3.0
  timescaledb-single:
  - apiVersion: v1
    created: "2020-01-08T11:03:18.429244947+01:00"
    description: TimescaleDB HA Deployment.
    digest: 2ae9d4a4ba25caf626e837244bf092721439e822d486f2c17f238b479012dedb
    home: https://github.com/timescale/timescaledb-kubernetes
    maintainers:
    - email: support@timescale.com
      name: TimescaleDB
    name: timescaledb-single
    sources:
    - https://github.com/timescale/timescaledb-kubernetes
    - https://github.com/timescale/timescaledb-docker-ha
    - https://github.com/zalando/patroni
    urls:
    - timescaledb-single-0.4.0.tgz
    version: 0.4.0
generated: "2020-01-08T11:03:18.426285493+01:00"
