# This file and its contents are licensed under the Apache License 2.0.
# Please see the included NOTICE for copyright information and LICENSE for a copy of the license.

name: mydb

accessNode: ts0

nodes:
  ts0:
    configuration: default
  ts1:
    configuration: data_node

configurations:
  default:
    postgresql:
      parameters:
        work_mem: 16MB
  data_node:
    postgresql:
      parameters:
        work_mem: 24MB